# Generated by Django 6.0.5 on 2026-06-06 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('load_balancer', 'Load Balancer')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning')], default='online', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('server_type', models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual'), ('container', 'Container'), ('cloud', 'Cloud')], default='physical', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('warning', 'Warning'), ('critical', 'Critical')], default='online', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_cores', models.IntegerField(default=1)),
                ('ram_gb', models.FloatField(default=1.0)),
                ('disk_gb', models.FloatField(default=50.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(help_text='Percentage 0-100')),
                ('memory_usage', models.FloatField(help_text='Percentage 0-100')),
                ('disk_usage', models.FloatField(help_text='Percentage 0-100')),
                ('network_in', models.FloatField(default=0.0, help_text='MB/s inbound')),
                ('network_out', models.FloatField(default=0.0, help_text='MB/s outbound')),
                ('cpu_temp', models.FloatField(blank=True, help_text='Celsius', null=True)),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.server')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
